[pytest]
# only the files with prefix `pytest_` would be recognized as pytest test scripts.
python_files = pytest_*.py

# Do not collect pytest_*.py shipped inside component manager checkouts
norecursedirs = managed_components

addopts =
  -s
  --embedded-services esp,idf
  --tb short

# ignore PytestExperimentalApiWarning for record_xml_attribute
filterwarnings =
  ignore::_pytest.warning_types.PytestExperimentalApiWarning

# log related
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# junit related
junit_family = xunit1
junit_logging = stdout
junit_log_passing_tests = False

markers =
  esp32: target esp32
  esp32s3: target esp32s3
  esp32p4: target esp32p4
  esp32s31: target esp32s31
